package com.tourismgov.report.service;

import com.tourismgov.report.client.*;
import com.tourismgov.report.dto.*;
import com.tourismgov.report.enums.ReportScope;
import com.tourismgov.report.model.Report;
import com.tourismgov.report.repository.ReportRepository;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class ReportServiceImpl implements ReportService {

    private final ReportRepository reportRepo;
    private final UserClient userClient;
    private final SiteClient siteClient;
    private final EventClient eventClient;
    private final ProgramClient programClient;
    private final ComplianceClient complianceClient;
    private final NotificationClient notificationClient;

    @Override
    @Transactional
    public ReportSummaryDTO generateReport(ReportRequestDTO request) {
        // 1. Identity Verification (Logic Unchanged)
        UserDTO requester = fetchUserSafely(request.getRequesterId());

        if (requester.getRole() == com.tourismgov.report.enums.Role.TOURIST) {
            throw new ResponseStatusException(
                HttpStatus.FORBIDDEN, 
                "Access Denied: Tourists are not authorized to generate government reports."
            );
        }

        // 2. Data Aggregation (Logic Unchanged)
        String reportMetrics = fetchMetricsByScope(request.getScope());

        StringBuilder reportLog = new StringBuilder();
        reportLog.append("--- OFFICIAL ").append(request.getScope()).append(" DATA LOG ---\n");
        reportLog.append("Generated By: ").append(requester.getName()).append(" (").append(requester.getRole()).append(")\n");
        reportLog.append("Date: ").append(LocalDateTime.now()).append("\n\n");
        reportLog.append(reportMetrics);

        // 3. Persistence (Logic Unchanged)
        Report savedReport = reportRepo.save(Report.builder()
                .scope(request.getScope())
                .metrics(reportLog.toString())
                .generatedByUserId(requester.getUserId())
                .generatedDate(LocalDateTime.now())
                .build());

        // ✅ UPDATED: Notification Logic to use DTO
        try {
            // Building the request object instead of sending individual params
            NotificationRequestDTO notificationReq = NotificationRequestDTO.builder()
                    .userId(requester.getUserId())       // Recipient
                    .entityId(savedReport.getReportId()) // Report ID
                    .subject("Report Generated")
                    .message("Your report for scope " + request.getScope() + " has been successfully generated.")
                    .category("SYSTEM")
                    .build();

            // Calling the updated Feign Client method
            notificationClient.createNotification(notificationReq); 
            log.info("Notification sent for report ID: {}", savedReport.getReportId());
            
        } catch (Exception e) {
            // Fault-tolerance preserved: report save succeeds even if notification fails
            log.error("Failed to send notification for generated report: {}", e.getMessage());
        }

        return mapToSummaryDTO(savedReport, requester.getName(), requester.getRole().name());
    }

    private String fetchMetricsByScope(ReportScope scope) {
        StringBuilder sb = new StringBuilder();
        try {
            switch (scope) {
                case SITE -> siteClient.getAllSites().forEach(s -> 
                    sb.append(String.format("SiteID: %d | Name: %s | Location: %s | Status: %s\n", 
                        s.getSiteId(), s.getName(), s.getLocation(), s.getStatus())));
                
                case EVENT -> eventClient.getAllEvents().forEach(e -> 
                    sb.append(String.format("EventID: %d | Title: %s | Location: %s | Date: %s | Status: %s\n", 
                        e.getEventId(), e.getTitle(), e.getLocation(), e.getDate(), e.getStatus())));
                
                case PROGRAM -> programClient.getAllPrograms().forEach(p -> 
                    sb.append(String.format("ProgID: %d | Title: %s | Budget: INR %s | Status: %s\n", 
                        p.getProgramId(), p.getTitle(), p.getBudget(), p.getStatus())));
                
                case COMPLIANCE -> complianceClient.getAllComplianceRecords().forEach(c -> 
                    sb.append(String.format("CompID: %d | EntityID: %d | Type: %s | Result: %s\n", 
                        c.getComplianceId(), c.getEntityId(), c.getType(), c.getResult())));
            }
        } catch (Exception e) {
            log.error("REPORTING ERROR: Failed to fetch data for scope {}. Reason: {}", scope, e.getMessage());
            sb.append("ERROR: The source service was unreachable. This report contains partial/empty data.");
        }
        return sb.toString();
    }

    @Override
    @Transactional(readOnly = true)
    public List<ReportSummaryDTO> getReportHistory(Long userId, ReportScope scope, LocalDate searchDate) {
        LocalDateTime start = (searchDate != null) ? searchDate.atStartOfDay() : null;
        LocalDateTime end = (searchDate != null) ? searchDate.atTime(23, 59, 59) : null;

        List<Report> myReports = reportRepo.findMyReports(userId, scope, start, end);
        
        if (myReports.isEmpty()) {
            return List.of();
        }

        UserDTO user = null;
        try {
            user = userClient.getUserById(userId);
        } catch (Exception e) {
            log.warn("User Service unreachable for history fetch. ID: {}", userId);
        }

        final String finalName = (user != null) ? user.getName() : "Unknown";
        final String finalRole = (user != null) ? user.getRole().name() : "N/A";

        return myReports.stream()
                .map(report -> mapToSummaryDTO(report, finalName, finalRole))
                .collect(Collectors.toList());
    }

    private UserDTO fetchUserSafely(Long userId) {
        try {
            UserDTO user = userClient.getUserById(userId);
            if (user == null) throw new ResponseStatusException(HttpStatus.NOT_FOUND, "User not found");
            return user;
        } catch (Exception e) {
            log.error("CRITICAL: User Service is down. Cannot verify requester ID: {}", userId);
            throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE, "Identity service is currently unreachable.");
        }
    }

    private ReportSummaryDTO mapToSummaryDTO(Report report, String name, String role) {
        return ReportSummaryDTO.builder()
                .reportId(report.getReportId())
                .scope(report.getScope())
                .generatedDate(report.getGeneratedDate())
                .generatedByName(name)
                .generatedByUserId(report.getGeneratedByUserId())
                .generatedByRole(role)
                .metrics(report.getMetrics())
                .build();
    }

    @Override
    public byte[] downloadReport(Long reportId) {
        return reportRepo.findById(reportId)
                .map(r -> r.getMetrics().getBytes())
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Report not found"));
    }
}